#!/usr/bin/env bash

set -Eeuo pipefail

usage() {
  cat <<'EOF'
Usage: run-cuda-clang-tidy.sh [OPTIONS] [FILENAME...]

OpenSn CUDA clang-tidy wrapper.

Runs clang-tidy against a CUDA-enabled build directory generated by CMake/nvcc. The script removes
nvcc-only command-line options from build/compile_commands.json before invoking clang-tidy.

Options:
  --build-dir PATH       CMake build directory. Defaults to build.
  --cuda-path PATH       CUDA toolkit root.
  --cuda-arch ARCH       CUDA architecture passed to clang-tidy, e.g. sm_89.
  --clang-arg ARG        Extra argument passed to clang in sanitized CUDA compile commands.
                         May be repeated.
  -h, --help             Show this help and exit.
EOF
}

build_dir="build"
cuda_path=""
cuda_arch=""
clang_args=()
positional=()

require_option_value() {
  local option="$1"
  local value="${2:-}"
  if [[ -z "$value" ]]; then
    echo "Error: '${option}' requires a value." >&2
    exit 2
  fi
}

normalize_path() {
  python3 -c 'from pathlib import Path; import sys; print((Path(sys.argv[1]) / sys.argv[2]).resolve() if not Path(sys.argv[2]).is_absolute() else Path(sys.argv[2]).resolve())' "$1" "$2"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --build-dir)
      require_option_value "$1" "${2:-}"
      build_dir="$2"
      shift 2
      ;;
    --build-dir=*)
      build_dir="${1#*=}"
      require_option_value "--build-dir" "$build_dir"
      shift
      ;;
    --cuda-path)
      require_option_value "$1" "${2:-}"
      cuda_path="$2"
      shift 2
      ;;
    --cuda-path=*)
      cuda_path="${1#*=}"
      require_option_value "--cuda-path" "$cuda_path"
      shift
      ;;
    --cuda-arch)
      require_option_value "$1" "${2:-}"
      cuda_arch="$2"
      shift 2
      ;;
    --cuda-arch=*)
      cuda_arch="${1#*=}"
      require_option_value "--cuda-arch" "$cuda_arch"
      shift
      ;;
    --clang-arg)
      require_option_value "$1" "${2:-}"
      clang_args+=( "$2" )
      shift 2
      ;;
    --clang-arg=*)
      clang_arg="${1#*=}"
      require_option_value "--clang-arg" "$clang_arg"
      clang_args+=( "$clang_arg" )
      shift
      ;;
    --) shift; positional+=( "$@" ); break ;;
    -*) echo "Error: unknown option '$1'." >&2; usage >&2; exit 2 ;;
    *) positional+=( "$1" ); shift ;;
  esac
done

invocation_dir=$(pwd -P)
repo=$(git rev-parse --show-toplevel)
if ! command -v python3 >/dev/null 2>&1; then
  echo "Error: 'python3' not found." >&2
  exit 127
fi
build_dir="$(normalize_path "$invocation_dir" "$build_dir")"
compile_commands="${build_dir}/compile_commands.json"
sanitized_build="${build_dir}/clang-tidy-cuda"
sanitized_compile_commands="${sanitized_build}/compile_commands.json"
cuda_files_list="${sanitized_build}/cuda-files.txt"

missing_options=()
[[ -n "$cuda_path" ]] || missing_options+=( "--cuda-path" )
[[ -n "$cuda_arch" ]] || missing_options+=( "--cuda-arch" )
if (( ${#missing_options[@]} > 0 )); then
  echo "Error: missing required option(s): ${missing_options[*]}" >&2
  usage >&2
  exit 2
fi

if [[ ! "$cuda_arch" =~ ^sm_[0-9]+[a-z]?$ ]]; then
  echo "Error: --cuda-arch must look like 'sm_89'; got '${cuda_arch}'." >&2
  exit 2
fi

if [[ ! -d "$cuda_path" ]]; then
  echo "Error: --cuda-path '${cuda_path}' is not a directory." >&2
  exit 2
fi
if [[ ! -f "${cuda_path}/include/cuda.h" ]]; then
  echo "Error: --cuda-path '${cuda_path}' does not contain include/cuda.h." >&2
  exit 2
fi
if [[ ! -f "$compile_commands" ]]; then
  echo "Error: '${compile_commands}' not found." >&2
  echo "       Configure a CUDA build first so CMake writes compile_commands.json." >&2
  exit 1
fi

if ! command -v run-clang-tidy >/dev/null 2>&1; then
  echo "Error: 'run-clang-tidy' not found." >&2
  echo "       Install clang-tidy (LLVM) or add 'run-clang-tidy' to your PATH." >&2
  exit 127
fi

mkdir -p "$sanitized_build"

python3 - "$compile_commands" "$sanitized_compile_commands" "$cuda_files_list" "$repo" "$cuda_path" "$cuda_arch" ${clang_args[@]+"${clang_args[@]}"} <<'PY'
import json
import os
from pathlib import Path
import shlex
import sys

path = sys.argv[1]
output_path = sys.argv[2]
cuda_files_path = sys.argv[3]
repo = sys.argv[4]
cuda_path = sys.argv[5]
cuda_arch = sys.argv[6]
extra_clang_args = sys.argv[7:]
compile_db_dir = Path(path).parent
with open(path, encoding="utf-8") as f:
    commands = json.load(f)
if not isinstance(commands, list):
    print(f"Error: '{path}' is not a JSON compilation database list.", file=sys.stderr)
    sys.exit(1)

drop_next_options = {
    "-arch",
    "-ccbin",
    "-diag-suppress",
    "-gencode",
    "-o",
    "-x",
    "-Xarchive",
    "-Xcompiler",
    "-Xlinker",
    "-Xnvlink",
    "-Xptxas",
    "--cuda-path",
    "--generate-code",
    "--offload-arch",
    "--options-file",
}
keep_next_options = {
    "-D",
    "-I",
    "-U",
    "-idirafter",
    "-imacros",
    "-include",
    "-iquote",
    "-isystem",
    "-isysroot",
    "--gcc-toolchain",
}
errors = []

def is_source_or_output(part):
    return (
        part.endswith(".cu")
        or part.endswith(".cuh")
        or part.endswith(".cc")
        or part.endswith(".cpp")
        or part.endswith(".cxx")
        or part.endswith(".o")
        or part.endswith(".obj")
    )

def is_compiler_launcher(part):
    name = os.path.basename(part)
    return name in {
        "nvcc",
        "clang",
        "clang++",
        "gcc",
        "g++",
        "cc",
        "c++",
        "mpicc",
        "mpicxx",
        "mpic++",
    }

def is_cuda_driver_option(part):
    return (
        part == "-c"
        or part == "--device-c"
        or part == "--device-link"
        or part == "-forward-unknown-to-host-compiler"
        or part == "--no-cuda-version-check"
        or part.startswith("-arch=")
        or part.startswith("-ccbin=")
        or part.startswith("-gencode")
        or part.startswith("-Xarchive")
        or part.startswith("-Xcompiler")
        or part.startswith("-Xlinker")
        or part.startswith("-Xnvlink")
        or part.startswith("-Xptxas")
        or part.startswith("--cuda-path=")
        or part.startswith("--expt-")
        or part.startswith("--generate-code")
        or part.startswith("--offload-arch=")
        or part.startswith("--options-file=")
        or part.startswith("-std=")
    )

def is_clang_tidy_compile_option(part):
    return (
        part.startswith("-D")
        or part.startswith("-U")
        or part.startswith("-I")
        or part.startswith("-isystem")
        or part.startswith("-iquote")
        or part.startswith("-idirafter")
        or part.startswith("-include")
        or part.startswith("--gcc-toolchain=")
        or part.startswith("-W")
        or part.startswith("-O")
        or part.startswith("-g")
        or part.startswith("-f")
        or part.startswith("-m")
        or part in {"-pthread", "-pipe", "-DNDEBUG"}
    )

def read_response_file(directory, value):
    rsp = Path(value)
    if not rsp.is_absolute():
        rsp = Path(directory) / rsp
    if not rsp.exists():
        errors.append(f"response file not found: {rsp}")
        return []
    return shlex.split(rsp.read_text(encoding="utf-8"))

def sanitize_parts(entry):
    directory = Path(entry.get("directory", compile_db_dir))
    if not directory.is_absolute():
        directory = compile_db_dir / directory
    parts = entry.get("arguments")
    if parts is None:
        if "command" not in entry:
            errors.append(f"{entry.get('file', '<unknown>')}: missing command/arguments")
            return []
        parts = shlex.split(entry["command"])
    if not isinstance(parts, list):
        errors.append(f"{entry.get('file', '<unknown>')}: arguments is not a list")
        return []
    if any(not isinstance(part, str) for part in parts):
        errors.append(f"{entry.get('file', '<unknown>')}: arguments contains a non-string value")
        return []

    expanded = []
    skip_next = False
    for part in parts:
        if skip_next:
            expanded.extend(read_response_file(directory, part))
            skip_next = False
            continue
        if part == "--options-file":
            skip_next = True
            continue
        if part.startswith("--options-file="):
            expanded.extend(read_response_file(directory, part.split("=", 1)[1]))
            continue
        if part.startswith("@") and part.endswith(".rsp"):
            expanded.extend(read_response_file(directory, part[1:]))
            continue
        if part.endswith(".rsp"):
            expanded.extend(read_response_file(directory, part))
            continue
        expanded.append(part)
    if skip_next:
        errors.append(f"{entry.get('file', '<unknown>')}: --options-file missing value")

    filtered = []
    skip_next = False
    keep_next = False
    for part in expanded:
        if is_compiler_launcher(part):
            continue
        if skip_next:
            skip_next = False
            continue
        if keep_next:
            filtered.append(part)
            keep_next = False
            continue
        if part in drop_next_options:
            skip_next = True
            continue
        if part in keep_next_options:
            filtered.append(part)
            keep_next = True
            continue
        if is_source_or_output(part):
            continue
        if is_cuda_driver_option(part):
            continue
        if is_clang_tidy_compile_option(part):
            filtered.append(part)
    if skip_next:
        errors.append(f"{entry.get('file', '<unknown>')}: option missing value")
    if keep_next:
        errors.append(f"{entry.get('file', '<unknown>')}: clang option missing value")
    return filtered

sanitized_commands = []
cuda_files = []
first_cuda_command = None

for original_entry in commands:
    if not isinstance(original_entry, dict):
        errors.append("compile_commands.json contains a non-object entry")
        continue

    entry = dict(original_entry)
    directory = Path(entry.get("directory", compile_db_dir))
    if not directory.is_absolute():
        directory = compile_db_dir / directory
    file_name = entry.get("file", "")
    if not isinstance(file_name, str):
        errors.append("compile_commands.json entry has a non-string file")
        continue
    if not file_name.endswith(".cu"):
        continue
    source_path = Path(file_name)
    if not source_path.is_absolute():
        source_path = directory / source_path
    source_path = source_path.resolve()
    if not source_path.exists():
        errors.append(f"source file not found: {source_path}")
        continue
    entry["file"] = str(source_path)

    filtered = sanitize_parts(entry)
    remaining_driver_tokens = [
        token
        for token in filtered
        if is_compiler_launcher(token) or token.endswith(".rsp") or token.startswith("@")
    ]
    if remaining_driver_tokens:
        errors.append(
            f"{entry['file']}: compile command still contains driver-only token(s): "
            + ", ".join(remaining_driver_tokens)
        )
    entry.pop("arguments", None)
    entry["command"] = shlex.join(
        [
            "clang++",
            "-x",
            "cuda",
            "-std=c++20",
            f"--cuda-path={cuda_path}",
            f"--offload-arch={cuda_arch}",
            "--no-cuda-version-check",
            "-Wno-unknown-cuda-version",
            "-D__NVCC__",
            f"-I{repo}",
            f"-I{repo}/external",
            f"-I{repo}/external/caribou",
            *extra_clang_args,
            *filtered,
            entry["file"],
        ]
    )
    if first_cuda_command is None:
        first_cuda_command = entry["command"]

    sanitized_commands.append(entry)
    cuda_files.append(entry["file"])

if errors:
    print("Error: CUDA compile command sanitization failed:", file=sys.stderr)
    for error in errors[:10]:
        print(f"  {error}", file=sys.stderr)
    if len(errors) > 10:
        print(f"  ... {len(errors) - 10} more", file=sys.stderr)
    sys.exit(1)

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(sanitized_commands, f, indent=2)
    f.write("\n")

with open(cuda_files_path, "w", encoding="utf-8") as f:
    for file in cuda_files:
        f.write(file)
        f.write("\n")

rewritten = len(sanitized_commands)
print(f"Sanitized {rewritten} CUDA compile command(s) in {output_path}", file=sys.stderr)
if first_cuda_command:
    print(f"First sanitized CUDA command: {first_cuda_command}", file=sys.stderr)
if rewritten == 0:
    print("Error: no CUDA compile commands were found to sanitize.", file=sys.stderr)
    sys.exit(1)
PY

cd "$repo"

header_filter="^${repo}/(framework|modules|python)/"
tmp_log="$(mktemp -t cuda_clang_tidy.XXXXXX)"
cleanup() { rm -f "$tmp_log"; }
trap cleanup EXIT

files=()
if (( ${#positional[@]} > 0 )); then
  for file in "${positional[@]}"; do
    if [[ "${file}" != *.cu ]]; then
      echo "Error: '${file}' is not a CUDA source file." >&2
      exit 2
    fi
    file="$(normalize_path "$invocation_dir" "$file")"
    if [[ ! -f "$file" ]]; then
      echo "Error: '${file}' does not exist." >&2
      exit 2
    fi
    if ! grep -Fxq -- "$file" "$cuda_files_list"; then
      echo "Error: '${file}' was not found in the sanitized CUDA compilation database." >&2
      echo "       Ensure it is part of the CUDA build target and rebuild compile_commands.json." >&2
      exit 1
    fi
    files+=( "$file" )
  done
else
  while IFS= read -r file; do
    files+=( "$file" )
  done < "$cuda_files_list"
fi

run-clang-tidy -p "$sanitized_build" -header-filter="$header_filter" "${files[@]}" \
  -warnings-as-errors='*' | tee -a "$tmp_log"

if grep -E '^[^:]+:[0-9]+:[0-9]+: (warning|error): ' "$tmp_log" >/dev/null; then
  echo "clang-tidy reported issues (treating warnings as errors)." >&2
  exit 1
fi
