#!/usr/bin/env bash

use_color=0
user_extra_before=""
user_extra_arg=""
positional=()
before_opt=()
arg_opt=()
clang_tidy_args=()
had_issues=0
tmp_log="$(mktemp -t clang_tidy.XXXXXX)"
cleanup() { rm -f "$tmp_log"; }
trap cleanup EXIT

set -Eeuo pipefail

usage() {
  cat <<'EOF'
Usage: run-clang-tidy.sh [-h] [-use-color] [-extra-arg-before=ARG] [-extra-arg=ARG] [FILENAME]

OpenSn-specific clang-tidy script.

Runs `run-clang-tidy` on the framework, modules, and python sources; you can specify a single
source file instead of running on the entire repository.

Examples (run from repository root):
  Analyze everything:
    tools/developer/run-clang-tidy.sh

  Analyze one file:
    tools/developer/run-clang-tidy.sh framework/utils/timer.cc

Options:
  -h, --help               Show this help text and exit.
  -use-color, --use-color  Enable colored output when supported.
  -extra-arg-before=ARG    Forward ARG before the file list (passed verbatim to llvm's run-clang-tidy).
  -extra-arg=ARG           Forward ARG after the file list.
EOF
}

# Parse command-line arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    -extra-arg-before=*)
      user_extra_before="${1#*=}"; shift; continue ;;
    -extra-arg-before)
      shift; user_extra_before="${1:-}"; [[ -n "${1:-}" ]] && shift; continue ;;
    -extra-arg=*)
      user_extra_arg="${1#*=}"; shift; continue ;;
    -extra-arg)
      shift; user_extra_arg="${1:-}"; [[ -n "${1:-}" ]] && shift; continue ;;
    -use-color|--use-color)
      use_color=1; shift; continue ;;
    --) shift; break ;;
    -*) echo "Unknown option: $1" >&2; usage; exit 2 ;;
    *) positional+=( "$1" ); shift; continue ;;
  esac
done

# Add color flag if requested
if (( use_color )); then
  clang_tidy_args+=( -use-color )
fi

# Collect anything after '--'
if [[ $# -gt 0 ]]; then positional+=( "$@" ); fi

if (( ${#positional[@]} > 1 )); then
  echo "Error: too many arguments" >&2
  usage
  exit 2
fi

if ! command -v run-clang-tidy >/dev/null 2>&1; then
  echo "Error: 'run-clang-tidy' not found." >&2
  echo "       Install clang-tidy (LLVM) or add 'run-clang-tidy' to your PATH." >&2
  exit 127
fi

repo=$(git rev-parse --show-toplevel)
header_filter="^${repo}/(framework|modules|python)/"


if [[ -n "${user_extra_before:-}" ]]; then
  before_opt=( -extra-arg-before="$user_extra_before" )
fi
if [[ -n "${user_extra_arg:-}" ]]; then
  arg_opt=( -extra-arg="$user_extra_arg" )
fi

if (( ${#positional[@]} == 1 )); then
  file="${positional[0]}"
  if [[ -f build/compile_commands.json ]]; then
    if ! grep -Fq -- "$file" build/compile_commands.json; then
      echo "Error: '$file' not found in build/compile_commands.json." >&2
      echo "       Ensure it’s part of a target and rebuild the DB." >&2
      exit 1
    fi
  fi
  run-clang-tidy ${clang_tidy_args[@]:-} -p build -header-filter="$header_filter" ${before_opt[@]+"${before_opt[@]}"} \
                 ${arg_opt[@]+"${arg_opt[@]}"} "$file" -warnings-as-errors='*' | tee -a "$tmp_log"
else
  run-clang-tidy ${clang_tidy_args[@]:-} -p build -header-filter="$header_filter" ${before_opt[@]+"${before_opt[@]}"} \
                 ${arg_opt[@]+"${arg_opt[@]}"} "${repo}/framework" "${repo}/modules" "${repo}/python" \
                 -warnings-as-errors='*' | tee -a "$tmp_log"
fi

# run-clang-tidy does not generate an exit status based on errors or warnings
# generated by clang-tidy. We'll have to do this ourselves by parsing the
# clang-tidy output.
if grep -E '^[^:]+:[0-9]+:[0-9]+: (warning|error): ' "$tmp_log" >/dev/null; then
  had_issues=1
fi

if (( ${had_issues} )); then
  echo "clang-tidy reported issues (treating warnings as errors)." >&2
  exit 1
fi
