name: github-pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ubuntu-22.04
    steps:
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          auto-update-conda: false
          channels: andrsd,defaults

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          conda install \
            cmake \
            make \
            mpich-mpicxx \
            doxygen \
            petsc==3.17.5 \
            vtk \
            lua \
            caliper \
            hdf5
          sudo pip install -r doc/requirements.txt

      - name: Build doco
        run: |
          cmake -S . -B ${{ github.workspace }}/build \
            -DOPENSN_WITH_DOCS=ON
          make -C ${{ github.workspace }}/build doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ github.workspace }}/build/doc/html
