name: Weekly Tests

on:
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v6
      - name: build
        shell: bash
        run: |
          module load python3/3.12.3 opensn/gcc/14
          mkdir build
          cd build
          cmake \
            -DBLAS_LIBRARIES="/opt/local/opensn/gcc/14.2.0/dependencies/lib/libf2cblas.a" \
            -DLAPACK_LIBRARIES="/opt/local/opensn/gcc/14.2.0/dependencies/lib/libf2cblas.a" \
            ..
          make -j

      - name: test
        shell: bash
        run: |
          module load python3/3.12.3 opensn/gcc/14
          mkdir -p "$RUNNER_TEMP/logs"
          test/run_tests -d test/python -j 32 -v 1 -w 4 \
            --run-log "$RUNNER_TEMP/logs/weekly_test_log.txt"
      - name: test unit
        shell: bash
        run: |
          module load python3/3.12.3 opensn/gcc/14
          build/test/opensn-unit
      - name: upload test logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: weekly-logs
          path: ${{ runner.temp }}/logs/*_log.txt
          if-no-files-found: ignore
          retention-days: 7
